version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Packaging app files...
      - zip -r app.zip . -x "app.zip"

artifacts:
  files:
    - app.zip
