version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install

  build:
    commands:
      - echo Build step completed

  post_build:
    commands:
      - echo Packaging application...
      - zip -r app.zip * .[^.]* -x "*.git*" "node_modules/*"
      - mv app.zip ../app.zip

artifacts:
  files:
    - ../app.zip
