version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Build completed on `date`

  post_build:
    commands:
      - echo Zipping app for Elastic Beanstalk...
      - zip -r app.zip * .[^.]* -x "*.git*" "node_modules/*"
      - mv app.zip ../app.zip

artifacts:
  files:
    - ../app.zip
